### ISSUE TITLE
[Bug] Borealis / Zombies completion percentage maxes at 144/252 complete camos; subsequent camo selections open the celebration pop-up every time

### ISSUE THREAD

**Issue by Storbie** [carlssonemil/interstellar#24]
Currently, the Borealis / Zombies completion percentage is calculated incorrectly. The website calculates the completion percentage based off of 144 total camos, when it should be based off of 252 total camos. This causes the Borealis completion message to pop up early before all camos have been selected.

Furthermore, once 144 Zombies camos have been completed, each camo selected _or_ deselected afterwards will bring up the completion celebration pop-up every single time, until less than 144 camos are shown as completed.

The Interstellar / Multiplayer section does not have this issue and is calculated properly. Both Multiplayer and Zombies have an identical number of unlockable camos for MW3 weapons.

**Comment by carlssonemil** [comment]
Looking into it straight away! Thanks for reporting!

**Comment by carlssonemil** [comment]
I've added a fix for this now, should be deployed to the app shortly! 🚀
