### ISSUE TITLE
Level MAX Check [Bug/Feature] 

### ISSUE THREAD

**Issue by emersondrw** [carlssonemil/interstellar#29]
Won't say a bug since isn't like its failing, but a check for max level in order to have the gun in track would be great.

**Comment by Voigtus** [comment]
Just a question to understand you correctly
You would like to have a view, where only the guns are "clickable", that you might have unlocked due to your player level?

**Comment by emersondrw** [comment]
Not player Lvl . a [ X ] in order to track if a gun is max level already. 
![image](https://github.com/carlssonemil/interstellar/assets/128835466/8eaedf91-515e-4321-b684-4d6ab9d1baed)
I know ppl is farming camos, but some players starts to level them 1st and then do the camo grind for example in this 2exp week.

**Comment by carlssonemil** [comment]
Thanks for the suggestion! Unfortunately, this is not something I think would fit the current UI of the tracker. I will close this as "not planned" for now, sorry.
