### ISSUE TITLE
Update Tac Eradicator 

### ISSUE THREAD

**Issue by jamesallnutt** [carlssonemil/interstellar#31]
Add new gun added pre-season one, TAC Eradicator, challenges as follows:

**Multiplayer**
- 50 kills - Spreading - level 2
- 10 penetration kills - Light Vision - level 9
- 10 full attachments - Palette Sands - level 15
- 10 double kills - Pyramidical - level 22
- Gilded: 2 kills without releasing trigger 10 times
- Forged: 3 kills without dying 10 times
- Priceless: 5 kills without dying 5 times

**Zombies**

-     250 kills - Pestilence - level 2
-     10 mangler kills - Unknown Visitor - level 9
-     10 kills without reloading 10 times - Palette Scorched - level 15
-     250 kills at Rare or higher Rarity - Mysterious - level 22
-     Enigma - 100 kills and extract
-     Scales - 300 kills and extract
-     Serpentinite - 10 special or elite kills

Camo files attached below (courtesy of @ItchyBeard) :
[taq-camos.zip](https://github.com/carlssonemil/interstellar/files/13507194/taq-camos.zip)

**Comment by carlssonemil** [comment]
Fixed in #33 😁
