### ISSUE TITLE
[Question] Will Zombies camo be supported?

### ISSUE THREAD

**Issue by cezarsmpio** [carlssonemil/interstellar#4]
Hey, as a big fan of zombies and I've been using your trackers since Damascus, it would be so much easier to have the tracker for zombies camos as well, similar to what you did with Cold War and Vanguard. Any plans to add it?

Thank you!

**Comment by carlssonemil** [comment]
Yes, I'll definitely add it! 😄

**Comment by cezarsmpio** [comment]
You the best!
