### ISSUE TITLE
The AR named "DG-58" in the app is actually called "DG-56" 

### ISSUE THREAD

**Issue by magnusfoldager** [carlssonemil/interstellar#45]
In MW3, the weapon with the multiplayer camos "Heat Map", "Creeplines", "Twilight Glitch", and "Oakleaf" - and the zombies camos "Typhoon", "Hysteria", "Hallowed Glitch", and "Petrified" - is actually called "DG-56" and not "DG-58" as in the app.

**Comment by magnusfoldager** [comment]
Created PR #46 to resolve.

**Comment by carlssonemil** [comment]
Closed in #46.
