### ISSUE TITLE
Wrong challenge for TAQ Evolvere Priceless Camo

### ISSUE THREAD

**Issue by mjdamato41** [carlssonemil/interstellar#57]
The tracker lists the challenge as "5 kills without Dying 5 times." In game, the challenge is listed as "Get 10 Double Kills while Fully Loaded with the TAQ Evolvere"

![Capture](https://github.com/carlssonemil/interstellar/assets/157408321/db4e401c-5e04-4617-9284-b1e6b18b387c)

**Comment by Spokkis** [comment]
I forgot to read through already open issues here.. But this applies to Forged Camo as well :)

**Comment by carlssonemil** [comment]
Fixed in #60.
