### ISSUE TITLE
[Bug]  TAQ EVOLVERE Forged/Priceless

### ISSUE THREAD

**Issue by Spokkis** [carlssonemil/interstellar#58]
First thing first, love the work u put into these camo trackers! 

2 wrong descriptions with the Forged and Priceless camo for the new TAQ EVOLVERE

Forged says x kills without dying x times, when the challenge is "Get 10 headshot kills while mounted"
Pricesless says x kills without dying x times, when the challenge is "Get 10 double kills with full attachments" (full attachments = 5 right? ) :P

**Comment by carlssonemil** [comment]
Fixed in #60.
