### ISSUE TITLE
[Bug] mastery progress sync

### ISSUE THREAD

**Issue by trexy07** [carlssonemil/interstellar#69]
Master progress from the multiplayer section dosen’t match the progress in the mastery tab

**Comment by matt-whiteley** [comment]
These pages are tracking different things.

The multiplayer tab is tracking progress to Interstellar camo, the Mastery tab is tracking progress towards the calling cards and charms you earn by getting many kills when using Gilded, Forged etc camos on a gun.

**Comment by carlssonemil** [comment]
As @matt-whiteley commented above, the progress bar at the bottom only tracks what is visible on the current page and does not track between different sections of the tracker! 😄
