### ISSUE TITLE
Camo requirement length breaks formatting on weapon cards

### ISSUE THREAD

**Issue by ItchyBeard** [carlssonemil/interstellar#7]
![image](https://github.com/carlssonemil/interstellar/assets/2664879/1b02e928-c674-4f57-9aec-c85f181654d7)
When in list view, long challenge text which breaks onto more than two lines, is cut off top and bottom. Perhaps either make it four columns instead of 5 on desktop, or truncate to a maximum character length I guess and append a … after it.

I feel if the string is less than or equal to 48 characters, it is fine.
If the string is more than 48 characters it should truncate to 48, and append a `…` to the end to show there is something more to read. The tooltip popover should continue to display the full text.

This is only an issue on desktop when the weapons are displayed in columns. In Tablet / Mobile view the weapon cards are full width and should not be truncated to 48 characters.

**Comment by carlssonemil** [comment]
I decreased the columns to 4 for now and will revisit this in the future if there are even longer requirements texts released 😄 Thanks for reporting! 🎉
