### ISSUE TITLE
[Bug] resets every time I open it

### ISSUE THREAD

**Issue by Kidney2002** [carlssonemil/interstellar#75]

**Comment by matt-whiteley** [comment]
Do you have your browser set to delete all browsing history/cookies/storage when you quit?

**Comment by carlssonemil** [comment]
@Kidney2002, are you still experiencing this issue after checking the settings that @matt-whiteley suggested above?

Also, are you on PC or mobile?

**Comment by Kidney2002** [comment]
No it’s all fixed now thanks

**Comment by carlssonemil** [comment]
Glad to hear!
