### ISSUE TITLE
[wrong challenge ]

### ISSUE THREAD

**Issue by V6Fuzzy** [carlssonemil/interstellar#79]
on the mors on the zombies tab the challeng is down for 250 kills with full attachments but the challenge is actully get 50 merc kills

**Comment by maeriens** [comment]
This is due to the WSP Stinger also having a camo called "Apocalyptic" so it's extracting the data from there. Might also be happening if there is another camos with same name for different guns.

**Comment by carlssonemil** [comment]
Should be fixed in #77!
