### ISSUE TITLE
Filters and "hide" buttons do not work

### ISSUE THREAD

**Issue by ItchyBeard** [carlssonemil/interstellar#8]
![image](https://github.com/carlssonemil/interstellar/assets/2664879/33eba9a3-9c3e-4945-ae34-5350acd34086)

**Comment by Voigtus** [comment]
Before we do double work: I would like to look into that. 
As far as a short analysis goes: when "updateFilters" is called on @change event, the "hideGilded" flag is undefined. Therefore it is deleted from the store, instead of being updated.

Regarding the category, I have not analyzed until now.

**Comment by carlssonemil** [comment]
Thanks for checking @Voigtus! I'll look into it now! 😄

**Comment by Voigtus** [comment]
As far as I understand it, you are you emit change="$emit('update:modelValue')"  in the FilterComponent.js, but the FiltersComponent.js is listening to a change event. At least after changing the emit value to 'change' I get a value that is not "undefined". Unfortunately still not the right one, but hey, babysteps....

**Comment by carlssonemil** [comment]
I copied most of this from the Orion tracker to save time in development, but the Orion tracker is built upon Vue 2 while I updated this tracker to Vue 3, so some of the v-model handling has changed between the two and I'm still not entirely up to speed on Vue 3 yet (we still use Vue 2 in my daily work as well 😅). I'll see if I can figure out how to do it with Vue 3 syntax 😄

**Comment by carlssonemil** [comment]
Fixed it! 🎉
